### PR TITLE
Add TTLB

### PR DESCRIPTION
**Pull request by pan-alexey**
Knowing the value of TTFB and TTLB, we can get another important metric - the time it takes for the server to send the entire content of the resource requested by the client. That is the difference between TTLB and TTFB.

### CODE REVIEW

**Comment by pan-alexey** [comment]
@googlebot I fixed it.

**Comment by pan-alexey** [comment]
@googlebot I fixed it.

**Comment by pan-alexey** [comment]
@googlebot I fixed it.

**Comment by philipwalton** [comment]
Thanks for the suggestion, but the intent of this library is not to include every performance metric that might be useful, it's to include all the field-measurable Web Vitals metrics. Time-to-last-byte is not a Web Vitals metric, so I don't think it makes sense to include it.

If you do want to track TTLB, there's [an example in the README](https://github.com/GoogleChrome/web-vitals#getttfb) of how to use the `entries` object passed to the `getTTFB()` callback, which—while perhaps less intuitive than a dedicated function—avoids the duplication of refetching the navigation entry, so that's what I'd recommend. (It's also [what I do](https://github.com/philipwalton/blog/blob/v3.1.0/assets/javascript/log.js#L266-L286) to track workerStart, responseEnd, DCL, and load on my blog).

**Pull request closed without merging**
